name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests + JaCoCo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run unit tests + JaCoCo report
        run: ./mvnw -B test jacoco:report

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          if-no-files-found: warn

  pit:
    name: PIT Mutation Testing
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Run PIT
        run: ./mvnw -B org.pitest:pitest-maven:1.17.1:mutationCoverage
      - name: Upload PIT report
        uses: actions/upload-artifact@v4
        with:
          name: pit-report
          path: target/pit-reports/
          if-no-files-found: warn

  acceptance:
    name: Karate acceptance tests
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Start Spring Boot (no tests)
        run: |
          ./mvnw -q -DskipTests spring-boot:run &
          echo "Waiting for app to be UP..."
          for i in {1..60}; do
            if curl -fsS http://localhost:8080/actuator/health | grep -q '"status":"UP"'; then
              echo "App is UP"; break
            fi
            sleep 2
          done

      - name: Run Karate acceptance tests
        run: ./mvnw -B -Pacceptance test

      - name: Upload Karate report
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports/
          if-no-files-found: warn

      - name: Stop app
        if: always()
        run: |
          pkill -f 'org.springframework.boot.loader.launch.JarLauncher' || true
          pkill -f 'spring-boot' || true
          pkill -f 'api-meli' || true
