name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit tests + JaCoCo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run unit tests + JaCoCo report
        run: ./mvnw -B test jacoco:report

      - name: Upload JaCoCo HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/**
          if-no-files-found: warn

      - name: Upload surefire reports (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**
          if-no-files-found: warn

  acceptance:
    name: Karate acceptance tests
    needs: unit-tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Start Spring Boot (no tests)
        run: |
          ./mvnw -q -DskipTests spring-boot:run &
          echo "Waiting for app to be UP..."
          for i in {1..60}; do
            if curl -fsS http://localhost:8080/actuator/health | grep -q '"status":"UP"'; then
              echo "App is UP"; exit 0
            fi
            sleep 2
          done
          echo "App did not start in time"; exit 1

      - name: Verify app is UP
        run: curl -fsS http://localhost:8080/actuator/health | grep '"status":"UP"'

      - name: Run Karate acceptance tests
        run: ./mvnw -B -Pacceptance test

      - name: Upload Karate report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports/**
          if-no-files-found: warn

      - name: Stop app
        if: always()
        run: |
          pkill -f 'org.springframework.boot.loader.launch.JarLauncher' || true
          pkill -f 'spring-boot' || true
          pkill -f 'api-meli' || true

  pit:
    name: PIT Mutation Testing
    needs: acceptance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      # Compila clases y test-classes (sin ejecutar tests)
      - name: Compile (classes + test-classes)
        run: ./mvnw -B clean test-compile -DskipTests=true

      # Ejecuta PIT (verbose para ver detalles)
      - name: Run PIT
        run: ./mvnw -B org.pitest:pitest-maven:mutationCoverage -Dpit.verbose=true

      # Mostrar logs de target
      - name: Inspect target
        if: always()
        run: ls -R target || true

      # Mostrar carpeta PIT (si existe)
      - name: Inspect PIT reports
        if: always()
        run: ls -R target/pit-reports || echo "pit-reports not found"

      # Subir reporte si existe
      - name: Upload PIT report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-report
          path: target/pit-reports/**
          if-no-files-found: warn


  performance:
    name: JMeter Performance Tests
    needs: unit-tests 
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Cache JMeter
        id: cache-jmeter
        uses: actions/cache@v3
        with:
          path: jmeter
          key: jmeter-5.6.3

      - name: Download JMeter
        if: steps.cache-jmeter.outputs.cache-hit != 'true'
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz -o jmeter.tgz
          tar -xvzf jmeter.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Prepare JMeter report folder
        run: mkdir -p target/jmeter-report target/jmeter-results || true

      - name: Run JMeter tests
        run: |
          ./jmeter/bin/jmeter -n \
            -t src/test/jmeter/test-plan-performance.jmx \
            -l target/jmeter-results.jtl \
            -e -o target/jmeter-report

      - name: Upload JMeter raw results (.jtl)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: target/jmeter-results.jtl
          if-no-files-found: warn

      - name: Upload JMeter HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: target/jmeter-report/**
          if-no-files-found: warn

  sonar:
    name: SonarCloud Analysis
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run SonarCloud analysis
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io

